### ISSUE TITLE
How to install this wayfire theme?

### ISSUE THREAD

**Issue by DarkevilPT** [bluebyt/Wayfire-dots#4]
I dont understand your instructions to install this theme.

If I have to extract the config folder into the wayfire one
if just wayfire.ini will do (clearly doesnt because.. the whole system turns to a broken one).

Is there any chance you make it easy to get hands on that beauty with dock working all night set?

**Comment by liumingedwin** [comment]
How silly you are:(
config --> .config and so on...
You can have a look at the installation script:)

**Comment by DarkevilPT** [comment]
![20240803_164125](https://github.com/user-attachments/assets/6da87721-3ed2-4a9e-a40f-fa6abac831ec)
What installation script ? theres no .sh script.
The files ive moved to the .config folder. But thats what happens.

Theres no indication to what needs to be installed manually just a few tips on settings which I dont get.. because it feels that I have to manually install about 14 apps just to get the .config files to work.. so.. meh.

Its one of those things... a genius made it.. but its just for shinning the ego.. screw the rest isnt it ? 😬

**Comment by liumingedwin** [comment]
Sorry. 
I checked the repo again. 
Copy Backgrounds here: ~/Pictures/Nord
Copy config to .config
Copy bin to .bin
Finally you need to modify the absolute path inside the files in .config.

**Comment by DarkevilPT** [comment]
I'll do this in a bit man! If this works !!! Thank you so much ! (I will try and update you next).

**Comment by DarkevilPT** [comment]
* Iron Bar: `acu install ironbar-git --noconfirm`

* [EWW Power Menu](https://dharmx.is-a.dev/eww-powermenu/) - fails to compile box
>acu -y install networkmanager eww-git
mkdir ~/.config/eww
cd ~/.config/eww
touch eww.yuck eww.scss

* Mako

* [Tokyonight-Dark](https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme) - Is it gtk3 gtk4-0 wheres the `assets` , `gtk.css` and `gtk-dark.css` ?
>acu -y install sassc gnome-tweaks gtk-engine-murrine
sudo git clone `https://github.com/Fausto-Korpsvart/Tokyonight-GTK-Theme.git
#cd ; mkdir themes`
sudo cp -r $HOME/Tokyonight-GTK-Theme/themes/* $HOME/themes
#sudo cp -r $HOME/Tokyonight-GTK-Theme/themes/* $HOME/.config/gtk-4.0
Apply using gnome-tweaks

* [Tela-circle-icon-theme](https://github.com/vinceliuice/Tela-circle-icon-theme#tela-circle-icon-theme)

>sudo git clone `https://github.com/vinceliuice/Tela-circle-icon-theme.git` ; cd Tela-circle-icon-theme ; bash ./install.sh

---

* [Fish shell](https://github.com/fish-shell/fish-shell) Command line shell 
* [Startship prompt](https://starship.rs/) Customizable prompt
Ive skipped them zsh I can do later

---

* [Catnip](https://github.com/iinsertNameHere/catnip)
>acu -y install catnap-git


* [SwayOSD](https://github.com/ErikReider/SwayOSD)
>acu -y install swayosd-git

* [Lite XL](https://lite-xl.com/)
>acu -y install lite-xl

* [Ulauncher](https://ulauncher.io/)
>git clone https://aur.archlinux.org/ulauncher.git && cd ulauncher && makepkg -is

---

* [Grimshot-pv](https://github.com/ferdiebergado/grimshot-pv)
Skipped this

* [Xava](https://github.com/nikp123/xava#programming-opengl-shaders) - Couldnt install this.

* [ncmpcpp](https://github.com/ncmpcpp/ncmpcpp) - I skipped this no need for a terminal music player

---

* [Swappy](https://github.com/jtheoof/swappy)
>acu -y install snappy-git

---
---

So... I tried to manually install all these shenenigans.. just to realize that most are in aur-git and probably because I am using an ARM SBC some fail to install and what not..

So the final conclusion is that.. It still didnt worked.. and its a mess.

**Comment by DarkevilPT** [comment]
// Install Wayfire

```
acu -y install freetype2 glm libdrm libevdev libgl libinput libjpeg libpng libxkbcommon libxml2 pixman wayland-protocols wlroots meson cmake doctest doxygen nlohmann-json libnotify base-devel pkg-config autoconf gobject-introspection gtk-layer-shell scour libdbusmenu-gtk3 gtkmm3 glib2-devel
git clone https://github.com/WayfireWM/wf-install.git
cd wf-install
bash ./install.sh --prefix /opt/wayfire --stream master
```

// Install dependencies
```
acu install ironbar-git eww-git mako-git tokyonight-gtk-theme-git fish starship catnap-git swayosd-git lite-xl xava-git swappy-git
sudo git clone https://github.com/vinceliuice/Tela-circle-icon-theme.git ; cd Tela-circle-icon-theme ; bash ./install.sh
git clone https://aur.archlinux.org/ulauncher.git && cd ulauncher && makepkg -is
#sudo git clone https://github.com/ncmpcpp/ncmpcpp.git ; cd ncmpcpp ; sudo ./autogen.sh ; sudo ./configure ; make ; make install ; make clean
```

// Install Bluebyt Nordic Theme

```
sudo git clone --depth=1  https://github.com/bluebyt/Wayfire-dots.git
sudo cp -r $HOME/Wayfire-dots/config/* $HOME/.config/
#cd Pictures ; mkdir Wallpaper ; cd Wallpaper ; mkdir Nord ; cd
sudo cp -r $HOME/Wayfire-dots/Wallpaper/* $HOME/Pictures/Wallpaper/Nord
sudo cp -r $HOME/Wayfire-dots/bin/* /usr/local/bin

```

// Update .config / .ini files

```
acu -y install emacs
sudo emacs $HOME/.config/wayfire.ini #update user bluebyt to ours
#launcher01 = /home/bluebyt/.bin/thunar.sh
sudo emacs $HOME/.config/wf-shell.ini #bunch of bluebyt user renaming to do here too
```

---

I still couldnt get it to work..

**Comment by bluebyt** [comment]
I don't provide any installer, you have to know to way around on Linux system file.

**Comment by DarkevilPT** [comment]
You know what? I couldnt give a fuck.. if the owner of the dotfile is not to bother explaining what he did tl achieve such fancy desktop environment and took the pleasure of even making youtube videos for that purpose just so in the end tells us users to fuck off and check on discord with others its just the short minded shit that doesnt even deserves attention.
The linux mentality.

**Comment by blacklightpy** [comment]
> Its one of those things... a genius made it.. but its just for shinning the ego.. screw the rest isnt it ? 😬

It's not like that. He made it, and he also shared it. Of course, he didn't take the time it takes to make sure that it runs on every other system. Did you pay him or something for that?

> You know what? I couldnt give a fuck.. if the owner of the dotfile is not to bother explaining what he did tl achieve such fancy desktop environment and took the pleasure of even making youtube videos for that purpose just so in the end tells us users to fuck off and check on discord with others its just the short minded shit that doesnt even deserves attention.
> The linux mentality.

There are plenty of other environments where they show you everything but won't give a single piece of the source code. That is, every proprietary software on this planet. I don't see you making this claim to Apple, because you know they wouldn't give a crap about your opinion, and somehow you feel that the Linux community should? Do you think a user of free software means a slave who will do everything for you?

I didn't get this working myself, but my approach was to add it to my to do list to fork this and refactor this better instead of being entitled like you. If you want to make things work, you have to put in the hours. This is how the Linux community works. Some guy shows and idea and gives you all he did to make it work, and you try to fix it until someday it works for everyone.

**Comment by DarkevilPT** [comment]
I forgot to reply to you because of work and Now im a bit hands tight But! If the thing is money say a price Ill donate but I want a proper step by step done to work out for everyone I think its only fair the rice gets proper shared ..

**Comment by blacklightpy** [comment]
@DarkevilPT 

The first thing you have to know is, not everyone is good at documenting stuff.

Secondly, I did take a look at it, and it includes a lot of configurations that are tailored to Arch Linux (which is not my distro, which is Void), and many aliases that the author personally prefers, but I don't, and also a backup Hyprland config. I'm gonna have to remove them and document them well.

Thirdly, some responses to your questions:

> I wonder.. does this needs to be this manual?

Yes, complex configurations will have to be very manual, at least on the part of the developer. But with a good documentation, it can be very easy to finish up. Building a script is hard because the necessary packages and package manager differ by the distros. Something like Nix flakes would be best for this purpose, although studying that ecosystem is a hurdle I haven't crossed yet.

Here's a guide I made for installing Aylur's AGS based widgets on Void Linux for an example: https://github.com/Aylur/dotfiles/issues/100.

This config would probably require more steps than that.

> Theres no indication to what needs to be installed manually just a few tips on settings which I dont get.. because it feels that I have to manually install about 14 apps just to get the .config files to work

The fact that there is no proper indication of what needs to be installed sucks, but he does list all the packages prior to installing dependencies.

But you'll usually have to manually install them, because some of them won't be inside the package manager. Now I'm not an Arch user, and I think this isn't usually a problem for Arch, where everything is in the AUR. But as a Void user with musl libc, I do things manually.

> If the thing is money say a price Ill donate but I want a proper step by step done to work out for everyone I think its only fair the rice gets proper shared

It's not about money, it's about time. He may not have enough time to make a documentation even if you could give him money. He shared his rice exactly as he uses on his PC, which is in this messy manner. It's not like he took his config and purposefully obscured it for others to use a premium package.

> "Follow focus and inactive-alpha" yet.

I noticed that this is part of the repo now, the README only has it as a rough note.

> If u somehow end up with a much nicer version of this feel free to tag/link me.

OK

**Comment by DarkevilPT** [comment]
Im curious about voidlinux too. Havent tried it yet. 
Like always everything is mostly directed to Arch Linux idk the reason or when in time people decided that arch linux was better than any other distro for customizations.. its kinda... random at times or hard to keep track these change in trendings.. hyprland now seems the trending DE to me window tilling isnt fun I love having a dock anyways.. wayfire to be at its finest could be if this rice worked.. But.. we need to be an google mankey to figure sh#t out.. as u said.. its a bunch of ... things..

If he come here and say pay me x and I will cook u way.
Sure. We could evaluate that. If price wise was duoable and he does it why not? The issue to me is that its not even on his best interest to do so and also as u said and I suspect its a whole messed up configs and dependancies and what not that will likely not make it easy to work.

**Comment by blacklightpy** [comment]
@DarkevilPT if it gets lost, let it. If someone showed you something beautiful and did not tell you how they made it, would you blame them for it?

Do you ask for source notes and composition files when listening to a song?

In this case the dude at least shared his code, and that's when you started blaming him.

Linux or free software does not mean "a group of people who are ready to do cool stuff and share it with everyone, making sure 5 year olds can make it work".

Free software simply means everyone can modify their system and "can" share their modifications. "Can", not "must". And even if people do share it, it does not have to be the most polished code. As I said, really interested people will pick it up and make it work.

The author of this repo does not have to do anything. His work is his intellectual property, and this is not even explicitly released under a free license, so he can claim copyright if he wants to. He just isn't doing so.

Anyways I don't think I can teach you normative ethics if you are this far off.

---

> idk the reason

That's a big problem here. You are new, yet you seem to have strong opinions on how the community is supposed to run. As far as I'm concerned, there is no reason except that Arch is rolling release and stays updated, and that allows for the AUR to function well without breaking many system packages like it would with point release distros.

> when in time people decided that arch linux was better than any other distro

No one decided that. It's just that Arch is the most customizable. Customizable does not mean good for everyone. For example, you do not find the freedom to customize good at all, because you do not want the freedom, you want it to be done for you by someone else.

That is, you do not want to customize yourself because doing so is hard. You prefer pre-made projects. So if Arch had something like a UI gallery, you would pick that. And turns out, the best we have gotten there is dedicated DEs like Plasma, GNOME, MATE, Cinnamon, Xfce, LXQt, etc.

> hyprland now seems the trending DE to me

Hyprland is not a DE. It is a dynamic tiling / floating Wayland compositor, and just that. That is, it includes only a window manager and compositing functions.

A DE includes a compositor, status bar, app launcher, etc.

> window tilling isnt fun

Then stop using tiling compositors or disable tiling in the ones that support it

> I love having a dock anyways

If you don't know to pick and choose a dock, compositors are not for you.

---

It seems to me like you want to use things that you do not understand and then make it other people's problem.

You do not know what a DE is, you hear that cool people use window managers and compositors instead of DEs, and so you want to jump there, and when nothing works, you blame those who make dotfiles.

It's like you'd walk into a court and ask why you can't be the judge, or ask your employer why you can't earn as much salary as the senior engineer, or ask people on Instagram why you can't get as many followers as Taylor Swift.

If you want the cool stuff, you have to put in the work. No, they can't make an easy to install setup, because that takes extra effort and they'll have to ensure that all packages required for it are installed.

They may make it available if they want to make it portable for themselves in the future. Or otherwise, they may just have muscle memory.

Also think about how you may later complain that some shortcut isn't working like you want it to and so you go about blaming the author for not documenting how to change shortcuts.

If you don't like what he's offering, make your own. That's what free software is about. "Freedom to modify your system". If you don't know how, that's your problem.

How stupid is this, someone worked hard to make something for their own personal use, and they gave some tips and sources to make it work, but you are so lazy that you end up blaming them?

**Comment by blacklightpy** [comment]
> If he came here and say pay me x and I will cook u the way sure. 

There are other people who'll do it. Find them and use their configs. Not everyone has to behave the way you want them to. Welcome to reality. Go out of your personal bubble sometimes and get to know other people a bit more. 

It's not even necessary to do that, it's just enough to know that there's a lot of things that people do that you don't do, and that's how the world stays in order. That simple knowledge is enough to know that everyone doesn't have to be just like you.
